 

import javax.swing.DefaultListModel;
import javax.swing.JList;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class Loans extends javax.swing.JPanel {
    /**
     * Creates new form NewJPanel
     */
    public Loans() {
        initComponents();
        //createLog();
        loadData();
        names.setVisible(false);
        jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        search_name = new javax.swing.JLabel();
        names = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        logFile = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 63, 30));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setFont(new java.awt.Font("Dubai", 2, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Loan Id", "Member Id", "Book Id", "Date Loaned", "Return Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setMinimumSize(new java.awt.Dimension(45, 80));
        jTable1.setName(""); // NOI18N
        jTable1.setPreferredSize(new java.awt.Dimension(400, 402));
        jTable1.setShowGrid(true);
        jScrollPane2.setViewportView(jTable1);

        jLabel3.setBackground(new java.awt.Color(0, 28, 0));
        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOAN DATA");

        Add.setBackground(new java.awt.Color(0, 0, 153));
        Add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Make a Loan");
        Add.setMaximumSize(new java.awt.Dimension(143, 23));
        Add.setMinimumSize(new java.awt.Dimension(143, 23));
        Add.setPreferredSize(new java.awt.Dimension(143, 30));
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(0, 0, 153));
        Update.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update a Loan");
        Update.setPreferredSize(new java.awt.Dimension(143, 30));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(0, 0, 153));
        Delete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete a Loan");
        Delete.setMaximumSize(new java.awt.Dimension(143, 23));
        Delete.setMinimumSize(new java.awt.Dimension(143, 23));
        Delete.setPreferredSize(new java.awt.Dimension(143, 30));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Felix Titling", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        search_name.setBackground(new java.awt.Color(153, 153, 255));
        search_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        search_name.setForeground(new java.awt.Color(0, 0, 0));
        search_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-interface-symbol (1).png"))); // NOI18N
        search_name.setText("Show loan number by name");
        search_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_name.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        search_name.setOpaque(true);
        search_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_nameMouseClicked(evt);
            }
        });

        names.setFont(new java.awt.Font("Loma", 1, 12)); // NOI18N
        names.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("jLabel2");

        logFile.setFont(new java.awt.Font("Dubai Light", 3, 18)); // NOI18N
        logFile.setText("Log File");
        logFile.setMaximumSize(new java.awt.Dimension(136, 23));
        logFile.setMinimumSize(new java.awt.Dimension(136, 23));
        logFile.setPreferredSize(new java.awt.Dimension(136, 23));
        logFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logFileActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Operation", "Timestamp", "User Id", "Load Id", "Member Id", "Book Id", "Date Loaned", "Return Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable2);

        jButton1.setFont(new java.awt.Font("Dubai Light", 3, 14)); // NOI18N
        jButton1.setText("Hide Log File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(search_name)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(names, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 543, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logFile, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(search_name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(names, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        add(jPanel1);

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        Object[] options1 = { "Submit", "Cancel" };
        Object[] options2 = { "New Submit", "Cancel" };
        
        JPanel panel = new JPanel();
        panel.setBackground(new java.awt.Color(255, 255, 203));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        //1o textfield
        panel.add(new JLabel("Loan Id:"));
        JTextField LidtextField = new JTextField(10);
        panel.add(LidtextField);
        
        //2o textfield
        panel.add(new JLabel("Member Id:"));
        JTextField MidtextField = new JTextField(10);
        panel.add(MidtextField);
        
        //3o textfield
        panel.add(new JLabel("Book Id:"));
        JTextField BidtextField = new JTextField(10);
        panel.add(BidtextField);
        
        //4o textfield
        panel.add(new JLabel("Date Loaned:"));
        JTextField DateLoanedtextField = new JTextField(10);
        panel.add(DateLoanedtextField);
        
        //5o textfield
        panel.add(new JLabel("Return Date:"));
        JTextField ReturnDatetextField = new JTextField(10);
        panel.add(ReturnDatetextField);

        int result2 = JOptionPane.YES_OPTION;
        int result = JOptionPane.YES_OPTION;
        
        
        while(result2 == JOptionPane.YES_OPTION && result == JOptionPane.YES_OPTION){   //AN PATISW NEW SUBMIT NA KANEI EPANALIPSI
          result = JOptionPane.showOptionDialog(null, panel, "Add a Loan",
            JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
            options1, null);
        
        if (result == JOptionPane.YES_OPTION) {
            
          try{
              //Pairnw tis times twn textfields
              int lid = Integer.valueOf(LidtextField.getText());
              int mid = Integer.valueOf(MidtextField.getText());
              int bid = Integer.valueOf(BidtextField.getText());
              String dateLoaned = DateLoanedtextField.getText();
              String returnDate = ReturnDatetextField.getText();
            
              insertLoan.setInt(1, lid);
              insertLoan.setInt(2, mid);
              insertLoan.setInt(3, bid);
              insertLoan.setString(4, dateLoaned);
              insertLoan.setString(5, returnDate);
                try{
                insertLoan.executeUpdate();
                }catch(Exception ex){
                        if(!ex.getMessage().equals("A result was returned when none was expected.")){
                            throw new Exception(ex);
                        }
                }
                JPanel panel2 = new JPanel();
                panel2.setBackground(new java.awt.Color(255, 255, 203));
                panel2.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

                panel2.add(new JLabel("Submission Successful"));

                result2 = JOptionPane.showOptionDialog(null, panel2, "Add a Loan",
                    JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                        options2, null);
              loadData(); //REFRESH 
          }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(),"Insert a Loan Error",JOptionPane.INFORMATION_MESSAGE);
                }
                //ADEIAZW TA PEDIA
                LidtextField.setText("");
                MidtextField.setText("");
                BidtextField.setText("");     
                DateLoanedtextField.setText("");   
                ReturnDatetextField.setText("");   
            }
        }//TELOS WHILE
    }//GEN-LAST:event_AddActionPerformed
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        Object[] options1 = { "Ok", "Cancel" };
        Object[] options2 = { "Update", "Cancel" };
        Object[] options3 = { "New Submit", "Cancel" }; 
        
        JPanel panel = new JPanel();
        panel.setBackground(new java.awt.Color(255, 255, 203));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        panel.add(new JLabel("Loan Id:"));
        JTextField LidtextField = new JTextField(10);
        panel.add(LidtextField);
        
        int result=JOptionPane.YES_OPTION;
        int result2=JOptionPane.YES_OPTION;
        int result3=JOptionPane.YES_OPTION;
        
        while(result3 == JOptionPane.YES_OPTION && result2 == JOptionPane.YES_OPTION && result == JOptionPane.YES_OPTION){   //AN PATISW NEW SUBMIT NA KANEI EPANALIPSI
          
            result = JOptionPane.showOptionDialog(null, panel, "Update a Loan",
        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
        options1, null);
        
        try{
             
            if (result == JOptionPane.YES_OPTION) {
                //Pairnw tin timh
                int lid = Integer.valueOf(LidtextField.getText());
                updateLoan.setInt(5, lid);
                
            
            JPanel panel2 = new JPanel();
            panel2.setBackground(new java.awt.Color(255, 255, 203));
            panel2.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
           
             //1o textfield    
             panel2.add(new JLabel("Member Id:"));
             JTextField MidtextField = new JTextField(10);
             panel2.add(MidtextField);

             //2o textfield
             panel2.add(new JLabel("Book Id:"));
             JTextField BidtextField = new JTextField(10);
             panel2.add(BidtextField);
             
             //3o textfield
             panel2.add(new JLabel("Date Loaned:"));
             JTextField dateLoanedtextField = new JTextField(10);
             panel2.add(dateLoanedtextField);
             
             //4o textfield
             panel2.add(new JLabel("Return date:"));
             JTextField returnDatetextField = new JTextField(10);
             panel2.add(returnDatetextField);
              
               result2 = JOptionPane.showOptionDialog(null, panel2, "Update Loan",
             JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
             options2, null);
          
             if(result2 == JOptionPane.YES_OPTION){
                try{
                    //Apothikevw tis arxikes times tou member pou thelw na kanw update
                    String selectString2 ="select * from getloanlid(?)";//SELECT * FROM loans where lid= ?
                    preSelect =  dbConnection.prepareStatement(selectString2); 
                    preSelect.setInt(1, lid);
                    rs2 = preSelect.executeQuery();

                    while(rs2.next()){
                    int mid0 = rs2.getInt("l_mid");
                    int bid0 = rs2.getInt("l_bid");
                    String dateLoaned0 = rs2.getString("d_loaned");
                    String returnDate0 = rs2.getString("r_date");

                    //Pairnw tis kainouries times
                    String mid = MidtextField.getText();
                    if(mid.equals(""))
                        mid = String.valueOf(mid0);

                    String bid = BidtextField.getText();
                    if(bid.equals(""))
                        bid = String.valueOf(bid0);

                    String dateLoaned =  dateLoanedtextField.getText();
                    if(dateLoaned.equals(""))
                        dateLoaned = String.valueOf(dateLoaned0);

                    String returnDate =  returnDatetextField.getText() ;
                    if(returnDate.equals(""))
                        returnDate = String.valueOf(returnDate0);
                      
                    //Kanw update
                    updateLoan.setInt(1,Integer.valueOf(mid));
                    updateLoan.setInt(2,Integer.valueOf(bid));
                    updateLoan.setString(3, dateLoaned);
                    updateLoan.setString(4, returnDate);
                    //try{
                    //updateLoan.executeUpdate();
                    //}catch(Exception ex){
                     //   System.out.println(ex.getMessage());
                    //}
                    }
                    
                    boolean did = updateLoan.execute(); //kanw update kai tautoxrona pairnw ton arithmo twn updates pou ginane
                    JPanel panel3 = new JPanel();
                    panel3.setBackground(new java.awt.Color(255, 255, 203));
                    panel3.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

                    if(!did) {
                        panel3.add(new JLabel("Loan not Found"));
                    }else{  
                        panel3.add(new JLabel("Submission Successful"));
                    result3 = JOptionPane.showOptionDialog(null, panel3, "Update a Loan"
                        ,JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                            options3, null);
                    }
                    loadData();
                    }catch(Exception ex){
                        JOptionPane.showMessageDialog(null, "Update a Loan Error","Update a Loan Error",JOptionPane.INFORMATION_MESSAGE);
                                        }
                        //ADEIAZW TA PEDIA
                        LidtextField.setText("");
                        MidtextField.setText("");
                        BidtextField.setText("");     
                        dateLoanedtextField.setText("");   
                        returnDatetextField.setText("");   
                   }
              }
        }catch(Exception ex){
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"Update a Loan Error",JOptionPane.INFORMATION_MESSAGE);
                                        }
        }//TELOS WHILE
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        Object[] options1 = { "Delete", "Cancel" };
        Object[] options2 = { "New Delete", "Cancel" };
        
        JPanel panel = new JPanel();
        panel.setBackground(new java.awt.Color(255, 255, 203));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        panel.add(new JLabel("Loan Id:"));
        JTextField LidtextField = new JTextField(10);
        panel.add(LidtextField);
        
        int result2 = JOptionPane.YES_OPTION;
        int result = JOptionPane.YES_OPTION;
 
        while(result2 == JOptionPane.YES_OPTION && result == JOptionPane.YES_OPTION){   //AN PATISW NEW SUBMIT NA KANEI EPANALIPSI
                result = JOptionPane.showOptionDialog(null, panel, "Delete a Loan",
                  JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                  options1, null);
              if (result == JOptionPane.YES_OPTION) {
                try{
                  //Pairnw thn timh
                  int lid = Integer.valueOf(LidtextField.getText());
                  //Kanw delete
                  deleteLoan.setInt(1, lid);
                  //try{
                  ResultSet rsr=null;
                  rsr =deleteLoan.executeQuery();
                  //}catch(Exception ex){
                    //  System.out.println(ex.getMessage());
                      //  if(ex.getMessage().equals("A result was returned when none was expected.")){
                        
                        //}else{
                             //System.out.println(ex);
                          //  throw new Exception(ex);
                        //}
                  //}
                  int exists=0;
                  while(rsr.next()){
                      exists = rsr.getInt("deleteloan");
                  }
                  JPanel panel2 = new JPanel();
                  panel2.setBackground(new java.awt.Color(255, 255, 203));
                  panel2.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
                  if(exists==0) 
                    panel2.add(new JLabel("Loan not Found"));

                  else
                    panel2.add(new JLabel("Deleted Successfully"));

                  result2 = JOptionPane.showOptionDialog(null, panel2, "Delete a Loan",
                      JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                          options2, null);
                  loadData(); //REFRESH
                  }catch(Exception ex){
                     JOptionPane.showMessageDialog(null, ex.getMessage(),"Delete a Loan Error",JOptionPane.INFORMATION_MESSAGE); 
                       }
                      //ADEIAZW TA PEDIA SE PERIPTWSI POU PATISA NEW SUBMIT
                      LidtextField.setText("");
                  }
        }//TELOS WHILE
    }//GEN-LAST:event_DeleteActionPerformed

    //KOUMPI POU KANEI VISIBLE ENA <JCOMBOBOX> STO OPOIO MPAINOUN MESA SAN 
    //VALUES OLA TA NAMES APO TO MEMBER TABLE TOU DATABASE DINAMIKA
    private void search_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_nameMouseClicked
       try {
           
            names.setVisible(true);
            statement =  dbConnection.createStatement();
            
            String selectString ="SELECT getfnamemember()";//SELECT first_name FROM member
            
            rs3 = statement.executeQuery(selectString);
            
            while(rs3.next()){
                String name = rs3.getString("getfnamemember");
                names.addItem(name);
            }
            
            statement.close();

            
        } catch (SQLException ex) {
            Logger.getLogger(Loans.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_search_nameMouseClicked

    private void namesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namesActionPerformed
        String name = String.valueOf(names.getSelectedItem());
        try {
            //System.out.println(name);
            
            String  Selectnames = " select getmemberloan(?)";//SELECT COUNT(*) FROM member m join loans l on m.mid=l.mid and first_name=?
            shownames = dbConnection.prepareStatement(Selectnames);
            shownames.setString(1, name);
            
            rss = shownames.executeQuery();
            while(rss.next()){
                int count1 = rss.getInt("getmemberloan");
                jLabel2.setText("Number of Loans " + name + " has is : " + count1);
            }
            jLabel2.setVisible(true);
            shownames.close();
        } catch (SQLException ex) {
            Logger.getLogger(Loans.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_namesActionPerformed

    private void logFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logFileActionPerformed
        jScrollPane5.setVisible(true);
        jButton1.setVisible(true);
    }//GEN-LAST:event_logFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jScrollPane5.setVisible(false);
        jButton1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
   
    static ResultSet rss = null;
    static PreparedStatement shownames=null;
    static ResultSet rs3 = null;
    public static Connection dbConnection = null;
    static Statement statement = null;
    static PreparedStatement preSelect = null;
    static ResultSet rs = null;
    static ResultSet rs2 = null;
    static PreparedStatement insertLoan = null;
    static PreparedStatement deleteLoan= null;
    static PreparedStatement updateLoan= null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logFile;
    private javax.swing.JComboBox<String> names;
    private javax.swing.JLabel search_name;
    // End of variables declaration//GEN-END:variables
     
    static Statement statement2 = null; //gia to gemisma tou pinaka log file
    static ResultSet rs5 = null; //gia to log file
    //Gemisma table Loans
    private void loadData() {
        jScrollPane5.setVisible(false);
        jButton1.setVisible(false);
        try{
            //anoigo tin sindesi
            //dbConnection = DriverManager.getConnection (Dashboard.url,Dashboard.username,Dashboard.passwd);
            
            //Insert loan //insert into loans(lid,mid,bid,date_loaned,return_date) values (?,?,?,?,?)
            String insertString = "select insertloan(?,?,?,?,?)";//
            insertLoan = dbConnection.prepareStatement(insertString);
            
            //Update loan
            String updateString = "select updateloan(?,?,?,?,?)";//select updateloan(?,?,?,?,?)//update loans set mid= ? , bid= ?, date_loaned= ?, return_date= ? where lid= ?
            updateLoan = dbConnection.prepareStatement(updateString);
            
            //Delete loan
            String deleteString = "select deleteloan(?)";//select deleteloan(?) //delete from loans where lid = ?
            deleteLoan = dbConnection.prepareStatement(deleteString);
            
            statement =  dbConnection.createStatement();
            String selectString ="select * from getloan()";//SELECT * FROM loans
            rs = statement.executeQuery(selectString);
            DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
            model1.setRowCount(0);
            
            while(rs.next()){
                int loanId = rs.getInt("l_lid");
                int memberId = rs.getInt("l_mid");
                int bookId = rs.getInt("l_bid");
                String dateLoaned = rs.getString("d_loaned");
                String returnDate = rs.getString("r_date");
                Object[] row = {loanId,memberId,bookId,dateLoaned,returnDate};
                model1.addRow(row);
            }
            
            String selectCount = "select getcountloan();";//Select COUNT(*) from loans
            rs = statement.executeQuery(selectCount);
            while(rs.next()){
                int count = rs.getInt("getcountloan");
                jLabel1.setText("Number of Loans: "+count);
            }
            statement.close();
             //Gemisw to log file
            try{
               statement2 = dbConnection.createStatement();
               String selectString2 = "select * from getloanslog()";//SELECT * from loans_log
               rs5 = statement2.executeQuery(selectString2);
               DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
               model2.setRowCount(0);

               while(rs5.next()){
                   String operation = rs5.getString("l_operation");
                   Timestamp stamp = rs5.getTimestamp("l_stamp");
                   String userid = rs5.getString("l_userid");
                   int lid = rs5.getInt("l_lid");
                   int mid = rs5.getInt("l_mid");
                   int bid = rs5.getInt("l_bid");
                   String dateLoaned = rs5.getString("d_loaned");
                   String returnDate = rs5.getString("r_date");
                   Object[] row = {operation,stamp,userid,lid,mid,bid,dateLoaned,returnDate};
                   model2.addRow(row);
               }
               statement2.close();
           }catch(SQLException ex){
               JOptionPane.showMessageDialog(null, ex.getMessage(),"LOG FILE LOAD DATA",JOptionPane.INFORMATION_MESSAGE);
           }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(),"LoansFrame",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    static boolean flag = true; //gia to log file table
    static Statement statement3 = null; //gia to call ths function createlog
    static void createLog() {
         //me to pou trexw to programma arxikopoieitai o pinakas log kai meta pou allazei to flag, ama allaksw tab kai epistrepsw sto loans frame, 
         //tote o pinakas den tha ksana arxikopoieithei kai tha diatirisei to periexomeno pou eixe 
            if(flag == true){
            //execute thn sql function create_loans_log()
            try{
                //anoigw tin sindesi
                dbConnection = DriverManager.getConnection (Dashboard.url,Dashboard.username,Dashboard.passwd);

                statement3 = dbConnection.createStatement();
                statement3.executeQuery("SELECT create_loans_log()");
                statement3.close();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(),"LOG FILE LOAD DATA",JOptionPane.INFORMATION_MESSAGE);
            }
            flag = !flag;
        }
    }
}
